[workspace.package]
authors = ["Cyborg Network <https://github.com/Cyborg-Network>"]
edition = "2021"
homepage = "https://cyborgnetwork.io/"
repository = "https://github.com/Cyborg-Network/cyborg-node/"

[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/worker-clusters",
    "pallets/task-management",
    "runtime",
    "orml/oracle",
    "orml/traits",
]
resolver = "2"

[workspace.dependencies]
log = { version = "0.4.21", default-features = false }
serde = { version = "1.0.197", default-features = false }
serde_json = { version = "1.0.114", default-features = false }
scale-info = { version = "2.11.1", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3.6.12", default-features = false, features = ["max-encoded-len"] }

orml-oracle = { path = "orml/oracle", default-features = false }
orml-traits = { path = "orml/traits", default-features = false }

# Local 
pallet-worker-clusters = { path = "pallets/worker-clusters", default-features = false, version = "0.1.0" }
pallet-task-management = { path = "pallets/task-management", default-features = false, version = "0.1.0" }

cumulus-pallet-xcm = { version = "0.14.0", default-features = false }
cumulus-primitives-core = { version = "0.14.0", default-features = false }
frame-benchmarking = { version = "35.0.0", default-features = false }
frame-support = { version = "35.0.0", default-features = false }
frame-system = { version = "35.0.0", default-features = false }
pallet-balances = { version = "36.0.0", default-features = false }
pallet-elections-phragmen = { version = "36.0.0", default-features = false }
pallet-message-queue = { version = "38.0.0", default-features = false }
pallet-preimage = { version = "35.0.0", default-features = false }
pallet-root-testing = { version = "11.0.0", default-features = false }
pallet-scheduler = { version = "36.0.0", default-features = false }
pallet-timestamp = { version = "34.0.0", default-features = false }
pallet-treasury = { version = "34.0.0", default-features = false }
pallet-xcm = { version = "14.0.0", default-features = false }
polkadot-parachain-primitives = { version = "13.0.0", default-features = false }
polkadot-runtime-common = { version = "14.0.0", default-features = false }
polkadot-runtime-parachains = { version = "14.0.0", default-features = false }
sp-api = { version = "33.0.0", default-features = false }
sp-application-crypto = { version = "37.0.0", default-features = false }
sp-arithmetic = { version = "26.0.0", default-features = false }
sp-core = { version = "34.0.0", default-features = false }
sp-io = { version = "37.0.0", default-features = false }
sp-runtime = { version = "38.0.0", default-features = false }
sp-runtime-interface = { version = "28.0.0", default-features = false }
sp-staking = { version = "33.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-storage = { version = "21.0.0", default-features = false }
xcm = { version = "14.0.0", package = "staging-xcm", default-features = false }
xcm-builder = { version = "14.0.0", package = "staging-xcm-builder", default-features = false }
xcm-executor = { version = "14.0.0", package = "staging-xcm-executor", default-features = false }

xcm-simulator = { version = "14.0.0" }