[relaychain]
default_command = "polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9955

[[parachains]]
id = 1000

[parachains.collator]
name = "alice"
rpc_port = 9988
command = "cyborg-node"
args = [
    "--offchain-worker always", 
    "--enable-offchain-indexing true", 
    "--log", "offchain=trace,logger=trace,runtime=trace,pallet_balances=trace,system=trace", 
    "-lparachain=debug"
]
