
//! Autogenerated weights for `pallet_edge_connect`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 39.0.0
//! DATE: 2024-09-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `SGOWMBP3`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cyborg-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet-edge-connect
// --extrinsic=*
// --steps=50
// --repeat=20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/edge-connect/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_edge_connect`.
pub trait WeightInfo {
	fn register_miner() -> Weight;
	fn remove_miner() -> Weight;
	fn update_oracle_status() -> Weight;
	fn penalize_miner() -> Weight;
	fn suspend_miner() -> Weight;
  fn ban_miner() -> Weight;
	fn update_operational_status() -> Weight;
  fn unsuspend_miner() -> Weight;
	fn request_maintenance() -> Weight;
	fn resolve_maintenance() -> Weight;
  fn add_account_authorized_for_registration() -> Weight;
  fn remove_account_authorized_for_registration() -> Weight;
}

/// Weights for `pallet_edge_connect` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EdgeConnect::AccountMiners` (r:1 w:1)
	/// Proof: `EdgeConnect::AccountMiners` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EdgeConnect::CloudMiners` (r:0 w:1)
	/// Proof: `EdgeConnect::CloudMiners` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn register_miner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3513`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `EdgeConnect::CloudMiners` (r:1 w:1)
	/// Proof: `EdgeConnect::CloudMiners` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn remove_miner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3688`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `EdgeConnect::WorkerClusters` (r:1 w:1)
	/// Proof: `EdgeConnect::WorkerClusters` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn update_oracle_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3688`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

 

	fn penalize_miner() -> Weight {
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	fn suspend_miner() -> Weight {
        Weight::from_parts(15_000_000, 3688)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    
    fn ban_miner() -> Weight {
        Weight::from_parts(10_000_000, 3688)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

	/// Storage: `EdgeConnect::WorkerClusters` (r:1 w:1)
	/// Proof: `EdgeConnect::WorkerClusters` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn update_operational_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3688`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
    
  fn unsuspend_miner() -> Weight {
    Weight::from_parts(10_000_000, 3688)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }

	fn request_maintenance() -> Weight {
		Weight::from_parts(13_000_000, 4200)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn resolve_maintenance() -> Weight {
		Weight::from_parts(12_000_000, 4300)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn add_account_authorized_for_registration() -> Weight {
		Weight::from_parts(12_000_000, 4300)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn remove_account_authorized_for_registration() -> Weight {
		Weight::from_parts(12_000_000, 4300)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `EdgeConnect::AccountMiners` (r:1 w:1)
	/// Proof: `EdgeConnect::AccountMiners` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EdgeConnect::CloudMiners` (r:0 w:1)
	/// Proof: `EdgeConnect::CloudMiners` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn register_miner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3513`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `EdgeConnect::CloudMiners` (r:1 w:1)
	/// Proof: `EdgeConnect::CloudMiners` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn remove_miner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3688`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	 /// Storage: `EdgeConnect::WorkerClusters` (r:1 w:1)
	/// Proof: `EdgeConnect::WorkerClusters` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn update_oracle_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3688`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn penalize_miner() -> Weight {
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn suspend_miner() -> Weight {
        Weight::from_parts(15_000_000, 3688)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    
    fn ban_miner() -> Weight {
        Weight::from_parts(10_000_000, 3688)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

	fn update_operational_status() -> Weight {
		Weight::from_parts(10_000_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
    
    fn unsuspend_miner() -> Weight {
        Weight::from_parts(10_000_000, 3688)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

	fn request_maintenance() -> Weight {
		Weight::from_parts(13_000_000, 4200)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn resolve_maintenance() -> Weight {
		Weight::from_parts(12_000_000, 4300)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn add_account_authorized_for_registration() -> Weight {
		Weight::from_parts(12_000_000, 4300)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn remove_account_authorized_for_registration() -> Weight {
		Weight::from_parts(12_000_000, 4300)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
}
