
//! Autogenerated weights for `pallet_task_management`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 39.0.0
//! DATE: 2024-07-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `LAPTOP-9PG2UJNC`, CPU: `AMD Ryzen 5 PRO 5650U with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/cyborg-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_task_management
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output=pallets/task-management/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_task_management`.
pub struct SubstrateWeight<T>(PhantomData<T>);

pub trait WeightInfo {
	fn task_scheduler(s: u32) -> Weight;
	fn submit_completed_task(s: u32) -> Weight;
	fn verify_completed_task(s: u32) -> Weight;
	fn resolve_completed_task(s: u32) -> Weight;
}

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EdgeConnect::AccountWorkers` (r:2 w:0)
	/// Proof: `EdgeConnect::AccountWorkers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::NextTaskId` (r:1 w:1)
	/// Proof: `TaskManagement::NextTaskId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EdgeConnect::WorkerClusters` (r:2 w:0)
	/// Proof: `EdgeConnect::WorkerClusters` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskStatus` (r:0 w:1)
	/// Proof: `TaskManagement::TaskStatus` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskAllocations` (r:0 w:1)
	/// Proof: `TaskManagement::TaskAllocations` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::Tasks` (r:0 w:1)
	/// Proof: `TaskManagement::Tasks` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskOwners` (r:0 w:1)
	/// Proof: `TaskManagement::TaskOwners` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn task_scheduler(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `271`
		//  Estimated: `6406`
		// Minimum execution time: 68_060_000 picoseconds.
		Weight::from_parts(72_013_947, 0)
			.saturating_add(Weight::from_parts(0, 6406))
			// Standard Error: 24_732
			.saturating_add(Weight::from_parts(249_832, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `TaskManagement::TaskAllocations` (r:1 w:0)
	/// Proof: `TaskManagement::TaskAllocations` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskStatus` (r:1 w:1)
	/// Proof: `TaskManagement::TaskStatus` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `EdgeConnect::WorkerClusters` (r:3 w:0)
	/// Proof: `EdgeConnect::WorkerClusters` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskVerifications` (r:0 w:1)
	/// Proof: `TaskManagement::TaskVerifications` (`max_values`: None, `max_size`: Some(221), added: 2696, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn submit_completed_task(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `587`
		//  Estimated: `9114`
		// Minimum execution time: 77_027_000 picoseconds.
		Weight::from_parts(94_590_233, 0)
			.saturating_add(Weight::from_parts(0, 9114))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TaskManagement::TaskStatus` (r:1 w:1)
	/// Proof: `TaskManagement::TaskStatus` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskVerifications` (r:1 w:0)
	/// Proof: `TaskManagement::TaskVerifications` (`max_values`: None, `max_size`: Some(221), added: 2696, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn verify_completed_task(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `3686`
		// Minimum execution time: 36_620_000 picoseconds.
		Weight::from_parts(48_025_385, 0)
			.saturating_add(Weight::from_parts(0, 3686))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TaskManagement::TaskStatus` (r:1 w:1)
	/// Proof: `TaskManagement::TaskStatus` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `TaskManagement::TaskVerifications` (r:1 w:0)
	/// Proof: `TaskManagement::TaskVerifications` (`max_values`: None, `max_size`: Some(221), added: 2696, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn resolve_completed_task(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `3686`
		// Minimum execution time: 37_311_000 picoseconds.
		Weight::from_parts(44_917_737, 0)
			.saturating_add(Weight::from_parts(0, 3686))
			// Standard Error: 14_277
			.saturating_add(Weight::from_parts(7_158, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
